### Vector Operations

In [2]:
import numpy as np

u = np.array([2,4,5,6])

In [3]:
2*u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1,0,0,2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v

array([ 2,  0,  0, 12])

### Vector x Vector Multiplication

In [8]:
v.shape[0]

4

In [12]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result


In [13]:
vector_vector_multiplication(u,v)

14.0

In [14]:
u.dot(v)

14

In [15]:
### Matrix Vector Multiplication

In [34]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [17]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [20]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] # ensure first dimension in U is equal to the 2nd dimension in v

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [21]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [22]:
U.dot(v)

array([14,  5,  5])

In [23]:
### Matric Matrix Multiplication

In [35]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [2, 1, 0],
    [2, 1, 0]
])

In [32]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

    

In [36]:
matrix_matrix_multiplication(U, V)

array([[24. , 15. ,  8. ],
       [ 7. ,  5. ,  4. ],
       [ 9. ,  6.5,  7. ]])

In [37]:
U.dot(V)

array([[24. , 15. ,  8. ],
       [ 7. ,  5. ,  4. ],
       [ 9. ,  6.5,  7. ]])

### Identity Matrix

In [42]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [2. , 1. , 0. ],
       [2. , 1. , 0. ]])

### Matrix Inverse A^-1A = I

In [45]:
V[[0,1,2]]

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [2. , 1. , 0. ]])

In [46]:
Vs = V[[0,1,2]]

In [47]:
np.linalg.inv(Vs)

array([[ 1. , -2. ,  0. ],
       [-2. ,  4. ,  1. ],
       [ 1. , -1. , -0.5]])

In [48]:
Vs_inv = np.linalg.inv(Vs)

In [49]:
Vs_inv

array([[ 1. , -2. ,  0. ],
       [-2. ,  4. ,  1. ],
       [ 1. , -1. , -0.5]])

In [50]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])