In [1]:
import numpy as np

### Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
a[2]

3

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Multi Dimensional Arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
n[2][1]

8

In [23]:
n[0,1]

2

In [24]:
n[0,2] = 20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[1]

array([4, 5, 6])

In [27]:
n[2] = [5,5,5]
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 5,  5,  5]])

In [29]:
n[:,2]

array([20,  6,  5])

In [30]:
n[:]

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 5,  5,  5]])

In [31]:
n[:,2] = [0,0,0]
n

array([[1, 2, 0],
       [4, 5, 0],
       [5, 5, 0]])

### Randomly Generated Arrays

In [34]:
np.random.rand(5,2)

array([[0.14415559, 0.59357763],
       [0.14321219, 0.30682742],
       [0.37533171, 0.549759  ],
       [0.48185215, 0.91765246],
       [0.58673193, 0.32673444]])

In [37]:
np.random.seed(2) # fix the random generator see, will get same results each time then
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
np.random.seed(2) # fix the random generator see, will get same results each time then
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [39]:
np.random.seed(2) # fix the random generator see, will get same results each time then
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [44]:
100 * np.random.rand(5,2)

array([[85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ],
       [50.52460901,  6.52865044],
       [42.81223276,  9.65309157],
       [12.71599717, 59.6745309 ]])

### Element-wise Operations

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a + 1

array([1, 2, 3, 4, 5])

In [42]:
a * 2

array([0, 2, 4, 6, 8])

In [59]:
b = 0.5 + (a / 2)
b

array([0.5, 1. , 1.5, 2. , 2.5])

In [49]:
a + b

array([10.    , 11.0025, 12.01  , 13.0225, 14.04  ])

In [51]:
a * b

array([ 0.    , 10.0025, 20.02  , 30.0675, 40.16  ])

In [52]:
a / b

array([0.        , 0.09997501, 0.1998002 , 0.29932652, 0.39840637])

### Comparison Operations

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [55]:
b

array([10.    , 10.0025, 10.01  , 10.0225, 10.04  ])

In [60]:
a > b

array([False, False,  True,  True,  True])

In [61]:
a[a > b]

array([2, 3, 4])

In [62]:
a.max()

4

In [63]:
a.min()

0

In [64]:
a.mean()

2.0

In [65]:
a.std()

1.4142135623730951

In [66]:
n.sum()

22