In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'1.5.3'

In [4]:
import pandas as pd

# Load data into a DataFrame from a CSV file
df = pd.read_csv('files/laptops.csv')


In [5]:
df.head(n=3)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   
2  ExpertBook  Intel Core i3    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0  
2        789.0

In [6]:
# Method 1: Using the shape attribute
num_records_shape = df.shape[0]
print(f"Number of records (using shape): {num_records_shape}")

# Method 2: Using the len function
num_records_len = len(df)
print(f"Number of records (using len): {num_records_len}")

Number of records (using shape): 2160
Number of records (using len): 2160


In [15]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [16]:
# Sums across each column
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [17]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [25]:
df['Screen'].median()

15.6

In [26]:
df['Screen'].describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: Screen, dtype: float64

In [28]:
df.groupby('Screen').Screen.count()

Screen
10.10       1
10.50       7
10.95       1
11.60      16
12.00       4
12.30      13
12.40       6
12.50       1
13.00      27
13.30     131
13.40      19
13.50      19
13.60      11
13.90       2
14.00     392
14.10      11
14.20      14
14.40       6
14.50       3
15.00      21
15.30       8
15.40       5
15.60    1009
16.00     174
16.10      48
16.20      10
17.00      33
17.30     161
18.00       3
Name: Screen, dtype: int64

In [29]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [33]:
df[df['Screen'].isnull()]

Laptop Status   Brand  \
624   Acer Extensa 15 EX215-54 Intel Core i5-1135G7/...    New    Acer   
1430  HP ENVY x360 2-in-1 Laptop 15-ew0008np Intel C...    New      HP   
1503  Lenovo IdeaPad Gaming 3 15ACH6 AMD Ryzen 5 560...    New  Lenovo   
1548  Lenovo ThinkPad P15 Gen 2 Intel Core i7-11850H...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type        GPU  Screen  \
624    Extensa  Intel Core i5    8      256          SSD        NaN     NaN   
1430      Envy  Intel Core i7   16      512          SSD   RTX 2050     NaN   
1503   IdeaPad    AMD Ryzen 5   16      512          SSD   RTX 3060     NaN   
1548  ThinkPad  Intel Core i7   16      512          SSD  RTX A2000     NaN   

     Touch  Final Price  
624     No       524.99  
1430   Yes      1863.52  
1503    No      1505.00  
1548    No      2569.00

In [35]:
df['Screen'].fillna(15.6, inplace=True)

In [36]:
df[df['Screen'].isnull()]

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [37]:
df['Screen'].median()

15.6

In [40]:
df[df['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [47]:
selected_columns = df[['Brand','Storage','Screen']]
selected_columns

Brand  Storage  Screen
0       Asus      512    15.6
1     Alurin      256    15.6
2       Asus      256    15.6
3        MSI     1000    15.6
4         HP      512    15.6
...      ...      ...     ...
2155   Razer     1000    17.3
2156   Razer     1000    17.3
2157   Razer     1000    17.3
2158   Razer     1000    13.4
2159   Razer      256    13.4

[2160 rows x 3 columns]

In [51]:
X = df[df['Brand'] == 'Innjoo'][['RAM','Storage','Screen']]
X

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

1478   1479  1480  1481   1482   1483
RAM        8.0    8.0   4.0   6.0    6.0    6.0
Storage  256.0  512.0  64.0  64.0  128.0  128.0
Screen    15.6   15.6  14.1  14.1   14.1   14.1

In [61]:
X

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [101]:
# Extract the values of the array ionto a variable so they can be multiplied
X_arr= X.values
X_arr

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [112]:
# XTX is the transpose of the X array of values
XTran = X_arr.T
XTran

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [54]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result


In [55]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] # ensure first dimension in U is equal to the 2nd dimension in v

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [59]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [114]:
XTX = matrix_matrix_multiplication(XTran,X_arr)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [115]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [116]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [117]:
MM = matrix_matrix_multiplication(XTX_inv,XTran)
MM

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [118]:
w = matrix_vector_multiplication(MM,y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [119]:
w.sum()

91.29988062995588